"""Create freebies table

Revision ID: 265054d7a7a1
Revises: 5f72c58bf48c
Create Date: 2024-03-18 03:00:20.526891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265054d7a7a1'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
